08:41:32.180 Running build in Washington, D.C., USA (East) – iad1
08:41:32.181 Build machine configuration: 2 cores, 8 GB
08:41:32.293 Cloning github.com/richardanderson697-boop/Automate-AI-v4 (Branch: main, Commit: 2a2a676)
08:41:32.294 Previous build caches not available.
08:41:32.486 Cloning completed: 193.000ms
08:41:33.067 Running "vercel build"
08:41:34.250 Vercel CLI 50.11.0
08:41:34.624 Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
08:41:34.625 Using pnpm@10.x based on project creation date
08:41:34.625 To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
08:41:34.658 Installing dependencies...
08:41:35.299 Lockfile is up to date, resolution step is skipped
08:41:35.371 Progress: resolved 1, reused 0, downloaded 0, added 0
08:41:35.420 Packages: +356
08:41:35.420 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
08:41:35.999  ENOTDIR  ENOTDIR: not a directory, mkdir '/vercel/path0/node_modules'
08:41:36.000 
08:41:36.001 pnpm: ENOTDIR: not a directory, mkdir '/vercel/path0/node_modules'
08:41:36.001     at async Object.mkdir (node:internal/fs/promises:856:10)
08:41:36.001     at async Promise.all (index 0)
08:41:36.001     at async headlessInstall (/pnpm10/node_modules/pnpm/dist/pnpm.cjs:150979:9)
08:41:36.001     at async tryFrozenInstall (/pnpm10/node_modules/pnpm/dist/pnpm.cjs:159380:60)
08:41:36.001     at async _install (/pnpm10/node_modules/pnpm/dist/pnpm.cjs:159174:37)
08:41:36.001     at async mutateModules (/pnpm10/node_modules/pnpm/dist/pnpm.cjs:159072:23)
08:41:36.001     at async install (/pnpm10/node_modules/pnpm/dist/pnpm.cjs:158964:77)
08:41:36.001     at async installDeps (/pnpm10/node_modules/pnpm/dist/pnpm.cjs:160908:67)
08:41:36.002     at async /pnpm10/node_modules/pnpm/dist/pnpm.cjs:194253:23
08:41:36.002     at async main (/pnpm10/node_modules/pnpm/dist/pnpm.cjs:194211:34)
08:41:36.053 Error: Command "pnpm install" exited with 236
